// CSRF Protection Middleware
import { doubleCsrf } from 'csrf-csrf';
import type { Request, Response, NextFunction } from 'express';
import { config } from '../config.js';

// Initialize CSRF protection
const csrfProtectionUtils = doubleCsrf({
  getSecret: () => config.csrfSecret,
  getSessionIdentifier: (req) => {
    // For stateless CSRF, use IP address as session identifier
    return req.ip || 'unknown';
  },
  cookieName: 'tz-csrf-token',
  cookieOptions: {
    sameSite: config.nodeEnv === 'production' ? 'none' : 'lax', // 'none' for cross-domain in production
    path: '/',
    secure: config.nodeEnv === 'production', // Required for sameSite: 'none'
    httpOnly: true,
  },
  size: 64,
  ignoredMethods: ['GET', 'HEAD', 'OPTIONS'],
});

const { generateCsrfToken, doubleCsrfProtection } = csrfProtectionUtils;

/**
 * Generates and returns a CSRF token for the client.
 *
 * This middleware should be attached to a GET endpoint (typically /api/csrf-token)
 * that the frontend calls on mount. The token is automatically generated by the
 * csrf-csrf library and set in an HTTP-only cookie.
 *
 * The frontend must:
 * 1. Call this endpoint to receive the token
 * 2. Include the token in the x-csrf-token header for state-changing requests
 *
 * @param req - Express request object (extended with csrfToken method)
 * @param res - Express response object
 */
export function csrfTokenGenerator(req: Request, res: Response) {
  // Generate the CSRF token and set the cookie
  const token = generateCsrfToken(req, res);
  res.json({
    token,
    success: true,
  });
}

/**
 * Validates CSRF tokens for state-changing requests.
 *
 * Uses double-submit cookie pattern for CSRF protection:
 * - Token in HTTP-only cookie (set by csrfTokenGenerator)
 * - Token in x-csrf-token header (sent by client)
 * - Both must match for request to proceed
 *
 * Automatically ignores safe methods (GET, HEAD, OPTIONS).
 * Can be disabled in development via config.csrfEnabled = false.
 *
 * Apply this middleware to all routes that modify state (POST, PUT, DELETE, PATCH).
 *
 * @param req - Express request object
 * @param res - Express response object
 * @param next - Express next function
 *
 * @example
 * router.post('/api/extraction/financials', csrfProtection, handler);
 */
export function csrfProtection(req: Request, res: Response, next: NextFunction) {
  // Skip CSRF in development if disabled
  if (config.nodeEnv === 'development' && !config.csrfEnabled) {
    console.log('[CSRF] Protection disabled in development');
    return next();
  }

  // Apply double CSRF token validation
  doubleCsrfProtection(req, res, next);
}

/**
 * Error handler middleware for CSRF validation failures.
 *
 * Catches CSRF validation errors and returns a user-friendly 403 response.
 * Should be registered as an error handling middleware in Express.
 *
 * If the error is not CSRF-related, passes it to the next error handler.
 *
 * @param err - Error object from CSRF validation
 * @param req - Express request object
 * @param res - Express response object
 * @param next - Express next function to pass non-CSRF errors
 *
 * @example
 * app.use(csrfErrorHandler);
 */
export function csrfErrorHandler(
  err: Error,
  req: Request,
  res: Response,
  next: NextFunction
) {
  if (err.message === 'invalid csrf token') {
    return res.status(403).json({
      error: 'Invalid CSRF token. Please refresh the page and try again.',
      status: 'error',
      code: 'CSRF_VALIDATION_FAILED',
    });
  }
  next(err);
}
